# Generated by Django 4.2.5 on 2023-09-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=255)),
                ('cpf_aluno', models.CharField(max_length=11)),
                ('rg_aluno', models.CharField(max_length=8)),
                ('matricula_aluno', models.CharField(max_length=8)),
                ('telefone_aluno', models.CharField(max_length=11)),
                ('email_aluno', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'Aluno',
                'ordering': ['nome_aluno'],
                'unique_together': {('nome_aluno', 'cpf_aluno', 'rg_aluno')},
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(max_length=255)),
                ('cod_disciplina', models.CharField(max_length=7)),
                ('carga_horaria_disciplina', models.IntegerField()),
                ('ementa_disciplina', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Disciplina',
                'ordering': ['nome_disciplina'],
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id_frequencia', models.AutoField(primary_key=True, serialize=False)),
                ('dia_frequencia', models.DateField(auto_now_add=True)),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.disciplina')),
            ],
            options={
                'db_table': 'Frequencia',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_professor', models.CharField(max_length=255)),
                ('cpf_professor', models.CharField(max_length=11)),
                ('rg_professor', models.CharField(max_length=8)),
                ('codigo_professor', models.CharField(max_length=8)),
                ('email_professor', models.EmailField(max_length=255)),
                ('telefone_professor', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Professor',
                'ordering': ['nome_professor'],
                'unique_together': {('nome_professor', 'cpf_professor', 'rg_professor')},
            },
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id_plano_aula', models.AutoField(primary_key=True, serialize=False)),
                ('tema_aula', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('metodo', models.CharField(max_length=50)),
                ('dia_plano_aula', models.DateField(auto_now_add=True)),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.disciplina')),
            ],
            options={
                'db_table': 'PlanoAula',
            },
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id_faluno', models.AutoField(primary_key=True, serialize=False)),
                ('presenca', models.BooleanField(default=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.aluno')),
                ('id_frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.frequencia')),
            ],
            options={
                'db_table': 'FrequenciaAluno',
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='id_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.professor'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('atividade', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('data_postagem', models.DateField(auto_now_add=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.disciplina')),
                ('id_plano_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.planoaula')),
            ],
            options={
                'db_table': 'Atividade',
                'ordering': ['data_postagem'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaAluno',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.aluno')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.disciplina')),
            ],
            options={
                'db_table': 'Matricula',
                'ordering': ['id_matricula', 'nota'],
                'unique_together': {('id_matricula', 'id_aluno')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('nome_disciplina', 'cod_disciplina')},
        ),
        migrations.CreateModel(
            name='AtividadeAluno',
            fields=[
                ('id_atv_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nota_atividade_aluno', models.FloatField(blank=True, null=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.aluno')),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.atividade')),
            ],
            options={
                'db_table': 'AtividadeAluno',
                'ordering': ['id_aluno', 'nota_atividade_aluno'],
                'unique_together': {('id_atv_aluno', 'id_atividade', 'id_aluno')},
            },
        ),
    ]
