# Generated by Django 4.2.5 on 2023-09-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id_postagem', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Abacaxi',
                'ordering': ['data', 'titulo'],
                'unique_together': {('data', 'titulo')},
            },
        ),
    ]
